controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

search_results:
    path: /search-results
    controller: App\Controller\SearchController::searchAction